### ISSUE TITLE
Sign up without .edu address

### ISSUE THREAD

**Issue by imagejan** [vanvalenlab/intro-to-deepcell#39]
Dear DeepCell team,

I noticed that in order to sign up for https://datasets.deepcell.org/, you need a mail address with a `.edu` domain. Unfortunately, there's no common identifier for mail addresses of academic institutions outside the US. How can I sign up with my own non-US institutional address?

**Comment by willgraf** [comment]
My apologies for the inconvenience - there are many academic domains that we did not anticipate! I have added "fmi.ch" as a valid domain, and you should be able to create an account now (If it doesn't work, try clearing your browser cache).

I'm going to close this issue but please re-open it if you run into any more registration issues.
