### ISSUE TITLE
Load data to train from scracth

### ISSUE THREAD

**Issue by xcarmengrandix** [vanvalenlab/intro-to-deepcell#41]
Hello,

I'm trying to use the training notebook to segment bright field images of hek293 cells. I have tif images that I labelled using a plugin in ImageJ. I didn't use DeepLabel because I was trying different scripts and most of them only require tif images. So my idea was to convert this labelled images into npz files that I could use in your notebook, but how the data have to be structured is a bit confusing for me. Could you please provide help on what a single npz file should contain in terms of source image and labelled image and how the data have to be organized inside each file?
Then I would load them using this script:

Training_set =  np.load("training_set.npz")
Testing_set =  np.load("testing_set.npz")

X_train = Training_set.f.X
y_train = Training_set.f.y
X_test = Testing_set.f.X
y_test = Testing_set.f.y

### Resizing
from deepcell.utils.data_utils import reshape_matrix

size = 256

X_train, y_train = reshape_matrix(X_train, y_train, reshape_size=size)
X_test, y_test = reshape_matrix(X_test, y_test, reshape_size=size)

print('X_train.shape: {}\nX_test.shape: {}'.format(
    X_train.shape, X_test.shape))

Thank you in advance for your help.

Best,
Carmen

**Comment by willgraf** [comment]
Closing this issue as question answered / stale.
