### ISSUE TITLE
Codes for training benchmark models

### ISSUE THREAD

**Issue by shan-stat** [vanvalenlab/intro-to-deepcell#44]
Hi, thanks for sharing codes about your great work, Mesmer!
In the paper, Mesmer was compared with several benchmark models, such as Cellpose, Mask R-CNN, etc.. I found codes for how to train Mesmer in your notebook, but I could not find codes for training each of the benchmark models. Did you share the codes somewhere? If not, could I get the codes? I would like to train the benchmarks models on your training setting. Thanks.

**Comment by ngreenwald** [comment]
Yup, they're all in the publications repo: https://github.com/vanvalenlab/publication-figures/tree/master/2021-Greenwald_Miller_et_al-Mesmer/notebooks/training

Let me know if you have any trouble finding a particular example

**Comment by shan-stat** [comment]
Hi Noah, 
Thanks for your quick response. Those notebooks are very helpful for me to replicate implementing the benchmark models.

First of all, I have tried to train Cellpose using the TissueNet dataset from https://datasets.deepcell.org. I first generated image and mask files using your function "save_as_fiffs", and then trained Cellpose on the resulting train and validation data but got the following error:
- "UserWarning: Using a target size (torch.Size([8, 510, 224, 224])) that is different to the input size (torch.Size([8, 2, 224, 224])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size."
- "RuntimeError: The size of tensor a (2) must match the size of tensor b (510) at non-singleton dimension 1"
The error seems to come from a shape of image and mask files.

1. Are the image and mask files what I generated different from data what you used in the notebook? I guess your training and validation data are '/deepcell_data/users/willgraf/mesmer_retrain/20201018_multiplex_seed_1_train_512x512.npz' and '/deepcell_data/users/willgraf/mesmer_retrain/20201018_multiplex_seed_1_val_256x256.npz'.

2. The training data what you used for training cellpose was also applied to your data augmentation strategies, like random flips, rotations, crops and scaling?

3. The resulting image and mask files what I generated are not a RGB image, but they have several channels and the shape of each channel looks like (512,2) for training or (256,2) for val. Are these files okay for training Cellpose?

**Comment by ngreenwald** [comment]
Hi Sunwoo, 
We apply our data augmentation online during training of Mesmer, not beforehand to the NPZ. Therefore, when training the cellpose model, the only data augmentation will be what is included during cellpose training, not anything described in our paper. 

The training images should be shape 512x512 x 2 channels, and the validation images should be shape 256x256x 2 channel. If instead you are getting images of shape 512x2, it might mean the wrong index is being selected for the channel vs the rows.

**Comment by shan-stat** [comment]
Hi Noah,
Thanks for the reply. I think I solved the shape problem, and cellpose model training works well now. 

Another question is about train, val and test splits. I have read the following thread, https://github.com/vanvalenlab/intro-to-deepcell/issues/43, but I think I missed some detail. 

TissueNet dataset is composed of train (2601 images), val (3140 images) and test (1249 images), but I think this is different from 80%, 10% and 10% splits, described in the paper. When you train cellpose model, how did you use the official splits? Did you combine all the images first and randomly split them into 80%, 10%, 10%?

**Comment by ngreenwald** [comment]
I think this is explained in #43 as well as the tissuenet readme, could you let me know which parts aren't clear about how the dataset is constructed?

**Comment by shan-stat** [comment]
Hi Noah, 
Sorry for making you repeat, but I would like to get more details about how the official splits (train: 2601, val: 3140, and test: 1249 images) can be matched to the splits of 80%, 10%, and 10%. 

I guess that when mesmer is trained, one train image (512x512) is cropped to four train images (256x256), so total number of train images after cropping is 2601x4=10404, correct? For the val split, your validation data generator does not keep augmented images, so the number of original images is about 3140/3=1048? At the end, the number of train/val/test images are about 10404/1048/1249, so the split ratio is about 80%/10%/10%?

If my guess is correct for training mesmer, the same strategy is applied to other benchmark models? E.g., for training cellphone, should I crop train images first and feed 256x256 train images to cellpose?

I could be wrong. If my understanding is incorrect, please let me know about a lit more explanation. Thanks!

**Comment by ngreenwald** [comment]
We used the same files for training all of the models. Mesmer, Cellpose, Stardist, etc. 

The train split is 512x512, so that it can be fed to our data generator. The val split is transformed from 512x512 to 256x256, because the validation data generator does not perform any cropping. We have three copies of the validation split: one at default resolution, one at increased resolution, and one at decreased resolution. This is why there are more images in the val split than expected, we do this to help the model work across different scales. 

The test split is 256x256 with no augmentations at all. 

Let me know if that wasn't clear or if you have any other questions.

**Comment by shan-stat** [comment]
Thanks for the response. It is very helpful, and I think I addressed the question.

**Comment by ngreenwald** [comment]
Sounds good, no problem
