### ISSUE TITLE
Can DeepCell be used to segment cell in the HE-stained images ?

### ISSUE THREAD

**Issue by februaryfang** [vanvalenlab/intro-to-deepcell#47]
Hi DeepCell Team,
I have a question regarding the use of DeepCell for a specific application. 
Recently, single-cell spatial transcriptomics and single-cell spatial HD technologies (e.g., 10x Genomics Visium) have become very popular. These technologies typically report data in units of spots or bins, which represent the average gene expression of all cells within a specific region. However, I have a requirement to identify individual cells from the corresponding HE-stained tissue images and obtain cell-level results. Specifically, I need to segment and identify each cell in the HE-stained images.Can DeepCell be used to achieve this? If so, are there any specific considerations or best practices for using DeepCell with HE-stained images?
Thank you for your help!
Best regards, februaryfang

**Comment by rossbar** [comment]
Generally speaking, Mesmer is not the right tool for cell segmentation on H&E images, as it requires a nuclear and a membrane/whole cell channel. You may be able to convert an H&E to such a format, but that's extra work on your part. IMO your best bet is to use a model that supports H&E segmentation directly, such as [cellSAM](https://www.biorxiv.org/content/10.1101/2023.11.17.567630v1).

I will close this as "answered" - hopefully that helps!
